### ISSUE TITLE
Error when issuing /cg test

### ISSUE THREAD

**Issue by hankur** [nsporillo/ColoredGroups#1]
No matter what group I want to test, it gives me the same error.

[15:00:02 INFO]: Nuhvu issued server command: /cg test abiomanik

org.bukkit.command.CommandException: Unhandled exception executing command 'cg' in plugin ColoredGroups v2.0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at java.lang.Thread.run(Thread.java:744) [?:1.8.0]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
        at net.porillo.ChatStyle.format(ChatStyle.java:28) ~[?:?]
        at net.porillo.ChatStyle.getExample(ChatStyle.java:33) ~[?:?]
        at net.porillo.ColoredGroups.getTestMessage(ColoredGroups.java:114) ~[?:?]
        at net.porillo.commands.TestCommand.runCommand(TestCommand.java:33) ~[?:?]
        at net.porillo.commands.CommandHandler.runCommand(CommandHandler.java:30) ~[?:?]
        at net.porillo.ColoredGroups.onCommand(ColoredGroups.java:50) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
        ... 15 more

**Comment by nsporillo** [comment]
Can you post your config.yml?

**Comment by hankur** [comment]
http://paste.ubuntu.com/11744573/
